#ifndef __RESOURCE_H__
#define __RESOURCE_H__

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

// Acceleration
#define IDA_MAIN 1

// Menu Id
#define IDM_MAIN 100
#define IDM_SETTINGS 102

// Dialogs
#define IDD_MAIN 100

// Main Dlg
#define IDC_TITLE_FOLDER 103
#define IDC_FOLDER 104
#define IDC_BROWSE_BTN 105
#define IDC_TITLE_SETTINGS 106
#define IDC_PREVIEW_FIELD 140
#define IDC_INCLUDEMOUSECURSOR_CHK 107
#define IDC_INCLUDEWINDOWSHADOW_CHK 108
#define IDC_CLEARBACKGROUND_CHK 109
#define IDC_TITLE_MODE 110
#define IDC_MODE_FULLSCREEN 111
#define IDC_MODE_WINDOW 112
#define IDC_MODE_REGION 113
#define IDC_SETTINGS 114
#define IDC_SCREENSHOT_SETTINGS 115
#define IDC_EXIT 116
#define IDC_COLOR 117
#define IDC_SCREENSHOT 118
#define IDC_TITLE_SCREENSHOT 119
#define IDC_TRACKBAR 120
#define IDC_SAVE_BTN 121

// Main Menu
#define IDM_TAKE_FULLSCREEN 134
#define IDM_TAKE_WINDOW 135
#define IDM_TAKE_REGION 136
#define IDM_EXPLORE 137
#define IDM_EXIT 138
#define IDM_ALWAYSONTOP_CHK 139
#define IDM_CHOOSE_COLOR 140
#define IDM_ABOUT 144

// Settings Menu
#define IDM_LOADONSTARTUP_CHK 154
#define IDM_COPYTOCLIPBOARD_CHK 156
#define IDM_PLAYSOUNDS_CHK 157
#define IDM_INCLUDEMOUSECURSOR_CHK 158
#define IDM_INCLUDEWINDOWSHADOW_CHK 159
#define IDM_CLEARBACKGROUND_CHK 160
#define IDM_FILENAME_INDEX 162
#define IDM_FILENAME_DATE 163

#define IDX_LANGUAGE 1000
#define IDX_FORMATS 2000

// Strings
#define IDS_FILE 3
#define IDS_EXPLORE 4
#define IDS_EXIT 5
#define IDS_VIEW 6
#define IDS_SCREENSHOT_SETTINGS 7
#define IDS_SETTINGS 8

#define IDS_HELP 9
#define IDS_COLOR 10
#define IDS_ABOUT 12

#define IDS_PREVIEW 117
#define IDS_ALWAYSONTOP_CHK 15

#define IDS_STARTMINIMIZED_CHK 18
#define IDS_LOADONSTARTUP_CHK 19
#define IDS_COPYTOCLIPBOARD_CHK 21

#define IDS_PLAYSOUNDS_CHK 23
#define IDS_INCLUDEMOUSECURSOR_CHK 24
#define IDS_CLEARBACKGROUND_CHK 25

#define IDS_MODE_FULLSCREEN 26
#define IDS_MODE_WINDOW 27
#define IDS_MODE_REGION 28

#define IDS_IMAGEFORMAT 29
#define IDS_FOLDER 30
#define IDS_QUICKSETTINGS 31
#define IDS_MODE 32
#define IDS_SCREENSHOT 33
#define IDS_DISABLE 35
#define IDS_WARNING_HOTKEYS 36
#define IDS_CANCEL 38
#define IDS_CLOSE 39
#define IDS_FILENAME 40
#define IDS_SAVE_EDITS 41
#define IDS_INCLUDEWINDOWSHADOW_CHK 46

// Wav
#define IDW_MAIN 1

// Icons
#define IDI_MAIN 100

#endif // __RESOURCE_H__
